apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ml-app
  namespace: ml-app-namespace
  labels:
    app: flask-ml-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-ml-app
  template:
    metadata:
      labels:
        app: flask-ml-app
    spec:
      containers:
        - name: flask-ml-container
          image: balesunilkumarreddy6321/my-flask-ml-app
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_ENV
              value: "production"
