apiVersion: v1
kind: Service
metadata:
  name: flask-ml-service
  namespace: ml-app-namespace
spec:
  selector:
    app: flask-ml-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5001
      nodePort: 30081  # Optional: specify a custom NodePort
  type: NodePort
