apiVersion: v1
kind: Service
metadata:
  name: flask-ml-service
  namespace: ml-app-namespace
spec:
  selector:
    app: flask-ml-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # Optional: specify a custom NodePort
  type: NodePort
